<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accueil</name>
   <tag></tag>
   <elementGuidId>440ce3d0-4137-4549-9df6-bddbbe23f34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sidebar-home-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sidebar-home-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6175846-3788-4139-baaf-22a5fb0ab46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebar-home-btn</value>
      <webElementGuid>c9ec7172-ba88-4e8e-a5e4-98b0891a5d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>3a0fe90a-db6d-4450-b35f-98cfb4328479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/home</value>
      <webElementGuid>4a19ecc3-174a-4102-8e1b-529e0a7cc893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accueil</value>
      <webElementGuid>737a02eb-11ce-4afa-89a1-6c25b4e0e8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-home-btn&quot;)</value>
      <webElementGuid>9bb61a03-f032-4e5d-8176-28011d7d7111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sidebar-home-btn']</value>
      <webElementGuid>2372b685-c1e1-4c3d-ab34-5ce131fff5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-menu']/li[3]/a</value>
      <webElementGuid>f4662cde-50ec-4d82-84ce-ab46d1e74c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se déconnecter'])[1]/following::a[2]</value>
      <webElementGuid>6d3f58b5-7d7a-420d-b377-f04646329a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guide utilisateur'])[1]/following::a[3]</value>
      <webElementGuid>393544aa-d248-4a91-a4c6-8f2a0eb9852d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alertes'])[1]/preceding::a[2]</value>
      <webElementGuid>7601ac8b-0012-431f-85cf-5830ef4a9e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/home')])[2]</value>
      <webElementGuid>88626d19-7c4c-4d68-8d1d-f5e8cb2a9766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/ul/li[3]/a</value>
      <webElementGuid>92c71054-f1fb-4f0a-8d55-050a4238a49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sidebar-home-btn' and @href = '/home' and (text() = 'Accueil' or . = 'Accueil')]</value>
      <webElementGuid>f72f87df-dfa0-4a60-98bb-96978b06df2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
