<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alertes</name>
   <tag></tag>
   <elementGuidId>6cbca341-3e0a-4af5-9b55-77546fcf5099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alert-managment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='alert-managment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df5973b7-4309-4aa9-99cb-48f48ee9afbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-managment</value>
      <webElementGuid>f5d13806-6707-41a1-81cc-83471cf39740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>78f7febd-94f3-4d49-ae9c-c4466cedb5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>bb19ea9f-92c8-4b10-b391-c0c1d1074b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alertes</value>
      <webElementGuid>14479eb4-50f3-48c1-baba-16f74fc064b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-managment&quot;)</value>
      <webElementGuid>4b968c84-c3da-44f6-8e67-cf3ca0ca70af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d94ede53-6940-49be-83a1-607d2ac19507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-managment</value>
      <webElementGuid>39997f4c-69fe-4352-b827-88185c927eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>bec7c2b9-5425-4433-864c-6e4c689b2f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>647a3349-35ef-4399-91e3-d97ae0c206d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alertes</value>
      <webElementGuid>f9b23ab4-82cb-4d3a-9a80-ee861590eb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-managment&quot;)</value>
      <webElementGuid>b5aa463b-6be9-4a82-acb7-67989aab61b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='alert-managment']</value>
      <webElementGuid>fbd206d0-18d2-4b27-be99-2c5af5ea1782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-menu']/li[5]/a</value>
      <webElementGuid>50f25b65-1636-4fe1-b814-5cc89e728fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accueil'])[1]/following::a[2]</value>
      <webElementGuid>2ff01171-ae5d-4042-8a5f-4f062dcd8ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se déconnecter'])[1]/following::a[4]</value>
      <webElementGuid>dd7988b6-0d14-40a2-bb1f-00e009df7b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documents'])[1]/preceding::a[1]</value>
      <webElementGuid>08c91530-7c2c-4983-bb39-756fd4d710e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app/user/settings/alerts')]</value>
      <webElementGuid>ea898a7c-da7e-424e-8e84-84bf6d65fd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/ul/li[5]/a</value>
      <webElementGuid>557524db-fbb2-4577-9ee3-46b9f60656c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'alert-managment' and @href = '/app/user/settings/alerts' and (text() = 'Alertes' or . = 'Alertes')]</value>
      <webElementGuid>f635c1c3-aac2-406e-bc5c-8bb05dc6bb9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
