<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alertes</name>
   <tag></tag>
   <elementGuidId>6cbca341-3e0a-4af5-9b55-77546fcf5099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alert-managment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='alert-managment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>badac864-924d-400c-bcd5-e622dd54f339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-managment</value>
      <webElementGuid>5fb1c291-b15b-4fb2-a602-b01893ffddcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>86d504bb-d452-4e2c-b2db-b27720e4d619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>4fae2a3f-b31b-46d2-985c-9fa4da72d318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alertes</value>
      <webElementGuid>4ff8fb42-cc46-43ef-b785-38e3f39b3956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-managment&quot;)</value>
      <webElementGuid>76202eaf-d1fc-4cc7-a995-76218c79e9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df5973b7-4309-4aa9-99cb-48f48ee9afbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-managment</value>
      <webElementGuid>f5d13806-6707-41a1-81cc-83471cf39740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>78f7febd-94f3-4d49-ae9c-c4466cedb5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>bb19ea9f-92c8-4b10-b391-c0c1d1074b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alertes</value>
      <webElementGuid>14479eb4-50f3-48c1-baba-16f74fc064b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-managment&quot;)</value>
      <webElementGuid>4b968c84-c3da-44f6-8e67-cf3ca0ca70af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d94ede53-6940-49be-83a1-607d2ac19507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-managment</value>
      <webElementGuid>39997f4c-69fe-4352-b827-88185c927eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>bec7c2b9-5425-4433-864c-6e4c689b2f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>647a3349-35ef-4399-91e3-d97ae0c206d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alertes</value>
      <webElementGuid>f9b23ab4-82cb-4d3a-9a80-ee861590eb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-managment&quot;)</value>
      <webElementGuid>b5aa463b-6be9-4a82-acb7-67989aab61b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='alert-managment']</value>
      <webElementGuid>bbeac68a-04ea-402a-bf84-2fe353bf4dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-menu']/li[5]/a</value>
      <webElementGuid>d3d27025-75eb-46a1-b9de-b3d1687a41b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accueil'])[1]/following::a[2]</value>
      <webElementGuid>a85808c1-7ce3-4c0d-8c92-deaa894c3f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se déconnecter'])[1]/following::a[4]</value>
      <webElementGuid>13329a9d-bd7f-46e0-982e-b9f53ef38f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documents'])[1]/preceding::a[1]</value>
      <webElementGuid>7594d6aa-743a-4f42-8018-62328ce11aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app/user/settings/alerts')]</value>
      <webElementGuid>3dd2acbd-b178-40fa-a526-20f78e79d4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/ul/li[5]/a</value>
      <webElementGuid>8e419440-fa55-4cde-96b4-8bdee03b6dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'alert-managment' and @href = '/app/user/settings/alerts' and (text() = 'Alertes' or . = 'Alertes')]</value>
      <webElementGuid>8d5d7928-fe75-4ecd-97d8-e58d0f211dcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
