<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alertes</name>
   <tag></tag>
   <elementGuidId>6cbca341-3e0a-4af5-9b55-77546fcf5099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alert-managment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='alert-managment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d94ede53-6940-49be-83a1-607d2ac19507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-managment</value>
      <webElementGuid>39997f4c-69fe-4352-b827-88185c927eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>bec7c2b9-5425-4433-864c-6e4c689b2f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app/user/settings/alerts</value>
      <webElementGuid>647a3349-35ef-4399-91e3-d97ae0c206d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alertes</value>
      <webElementGuid>f9b23ab4-82cb-4d3a-9a80-ee861590eb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-managment&quot;)</value>
      <webElementGuid>b5aa463b-6be9-4a82-acb7-67989aab61b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='alert-managment']</value>
      <webElementGuid>a00b70bc-ae93-441b-b4cb-2e2b7b417e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebar-menu']/li[5]/a</value>
      <webElementGuid>985b5bec-a514-4b56-9df8-d04221af1788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accueil'])[1]/following::a[2]</value>
      <webElementGuid>029eec32-ee32-4d9c-9e91-ceda147218f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se déconnecter'])[1]/following::a[4]</value>
      <webElementGuid>8a685c57-ef69-4a63-a9f5-8403c772748b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documents'])[1]/preceding::a[1]</value>
      <webElementGuid>3da89973-f1b1-4eec-a78d-b9ce3638e15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app/user/settings/alerts')]</value>
      <webElementGuid>ee0e156d-6e03-4082-ba71-e69bd80772ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/ul/li[5]/a</value>
      <webElementGuid>add55379-a198-494d-8378-6d85946c0d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'alert-managment' and @href = '/app/user/settings/alerts' and (text() = 'Alertes' or . = 'Alertes')]</value>
      <webElementGuid>da6c74cd-4aa4-4687-801a-a491a246d2a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
