<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Alertes_fa fa-file</name>
   <tag></tag>
   <elementGuidId>6fcdf8c0-5ca4-4264-b93d-fb4dd1110d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='user-guide']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-file</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>087e8bbb-5cb9-4fa0-a5d2-594e7f5103f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Documents</value>
      <webElementGuid>155013d9-6083-4cae-a39a-2a2b8d760602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-file</value>
      <webElementGuid>75db858f-fe5c-4fb6-9cb3-081b7e5b1941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-guide&quot;)/span[@class=&quot;fa fa-file&quot;]</value>
      <webElementGuid>581b92df-0929-452f-8783-019e3661d76c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='user-guide']/span</value>
      <webElementGuid>ea215d6a-a7ce-4520-896f-f3d9cdc73136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span</value>
      <webElementGuid>5d06ec14-4b69-466a-94a0-ca9ad6ff5df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Documents']</value>
      <webElementGuid>0baf1493-1741-4dcf-9dd1-da08b5f78d16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
