<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_42 - Renseignement dinformations de fa_66e06c</name>
   <tag></tag>
   <elementGuidId>3b41380c-c782-4fd1-9beb-dffaeec4c50d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corp']/app-settings/div/div[3]/app-my-alert/div/div/app-alerts/fieldset/div/form/div[16]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>59aa510e-d55d-4734-b1bf-34e49d89d599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2</value>
      <webElementGuid>d39cfde9-b45b-442a-b7a8-48d14dfdfd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 42 - Renseignement d'informations de facturation </value>
      <webElementGuid>c2bc79c3-1573-4ec0-9f40-dd28f4d9b777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-my-alert[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-md-12 padding-top-15&quot;]/div[@class=&quot;panel-body margin-top-4&quot;]/app-alerts[@class=&quot;ng-star-inserted&quot;]/fieldset[@class=&quot;fieldset mails-config border-0&quot;]/div[@class=&quot;col-md-12 col-xs-12 margin-top-5&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;row form-group ng-star-inserted&quot;]/span[@class=&quot;col-md-2&quot;]</value>
      <webElementGuid>48a29e65-9e45-4f6b-883c-d8410b1ed650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-my-alert/div/div/app-alerts/fieldset/div/form/div[16]/span</value>
      <webElementGuid>54a770f5-1352-4060-85d4-8c4ed2863cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('38 - Mise à jour d', &quot;'&quot;, 'un dossier de transport')])[1]/following::span[2]</value>
      <webElementGuid>4c30d75d-55d6-42c1-b168-69bb6425f173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('37 - Création d', &quot;'&quot;, 'un dossier de transport')])[1]/following::span[3]</value>
      <webElementGuid>1decc5ea-526d-4885-9fa1-9ccd75f16d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('43 - Partage d', &quot;'&quot;, 'information')])[1]/preceding::span[1]</value>
      <webElementGuid>c655743e-e558-44d3-a990-b18c0fe91f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('66 - Création d', &quot;'&quot;, 'une commande')])[1]/preceding::span[8]</value>
      <webElementGuid>4db31c11-8fb1-4474-a561-a1438405dbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/span</value>
      <webElementGuid>9b4aaf23-74e6-47df-a899-0cfb99c26465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot; 42 - Renseignement d&quot; , &quot;'&quot; , &quot;informations de facturation &quot;) or . = concat(&quot; 42 - Renseignement d&quot; , &quot;'&quot; , &quot;informations de facturation &quot;))]</value>
      <webElementGuid>856b725e-e3eb-4ec9-b694-e23080f0ee02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
