<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Compliance Matrix_fa fa-cog</name>
   <tag></tag>
   <elementGuidId>ee749b74-fdad-4ac6-9286-768d9d43aeb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Settings']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-cog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>12e0f2d9-9b34-44e8-abec-0685d9dc7d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-cog</value>
      <webElementGuid>03a28e11-6256-470e-aa08-56c893421e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Paramètres</value>
      <webElementGuid>babd919f-cdf3-49c7-8ffd-0ddf0c8a4c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Settings&quot;)/span[@class=&quot;fa fa-cog&quot;]</value>
      <webElementGuid>b5fd4173-1505-4762-8313-f2331fd38771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Settings']/span</value>
      <webElementGuid>6bf62150-8906-44e2-91f9-4bb19ba0a357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/span</value>
      <webElementGuid>f45c2e68-ca5e-4861-a922-24eb2b69f455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Paramètres']</value>
      <webElementGuid>d25025c8-e708-4f1a-827c-9f44596ccf4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
