<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_43 - Partage dinformation</name>
   <tag></tag>
   <elementGuidId>8ad2459e-79eb-4045-a091-5b6afb7b817b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='corp']/app-settings/div/div[3]/app-my-alert/div/div/app-alerts/fieldset/div/form/div[17]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6c8c290e-9f11-46b1-aa8d-2b9ff801f208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2</value>
      <webElementGuid>a5299932-d768-4ea3-bc33-d96aebb8b94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 43 - Partage d'information </value>
      <webElementGuid>95a45b93-83a1-4f69-ba57-e85b0b563bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-settings[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;settings-root&quot;]/div[@class=&quot;settings-content&quot;]/app-my-alert[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-md-12 padding-top-15&quot;]/div[@class=&quot;panel-body margin-top-4&quot;]/app-alerts[@class=&quot;ng-star-inserted&quot;]/fieldset[@class=&quot;fieldset mails-config border-0&quot;]/div[@class=&quot;col-md-12 col-xs-12 margin-top-5&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;row form-group ng-star-inserted&quot;]/span[@class=&quot;col-md-2&quot;]</value>
      <webElementGuid>3201d167-8a3e-4fcd-b427-154385787a66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-settings/div/div[3]/app-my-alert/div/div/app-alerts/fieldset/div/form/div[17]/span</value>
      <webElementGuid>18473eaa-6f4e-4303-b762-7bb7b3ec6da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('42 - Renseignement d', &quot;'&quot;, 'informations de facturation')])[1]/following::span[1]</value>
      <webElementGuid>3b9ecd3d-c69e-4372-af7e-66de7337cf46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('38 - Mise à jour d', &quot;'&quot;, 'un dossier de transport')])[1]/following::span[3]</value>
      <webElementGuid>2aa9d99e-2755-44eb-898a-4b95f3053fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('66 - Création d', &quot;'&quot;, 'une commande')])[1]/preceding::span[7]</value>
      <webElementGuid>1af13cd8-ac62-44d9-acc2-09ac27670659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('67 - Validation d', &quot;'&quot;, 'une commande')])[1]/preceding::span[8]</value>
      <webElementGuid>5478331f-57e4-4821-8a48-198b98d7b82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/span</value>
      <webElementGuid>4f87a6b3-8b21-4a9f-9f10-76d5ebe01cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot; 43 - Partage d&quot; , &quot;'&quot; , &quot;information &quot;) or . = concat(&quot; 43 - Partage d&quot; , &quot;'&quot; , &quot;information &quot;))]</value>
      <webElementGuid>35f5cfa5-2f07-4c1c-99ae-4b799880c71a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
