<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Accueil_sidebar-alert</name>
   <tag></tag>
   <elementGuidId>048d67b4-e71e-4048-bea5-8e950878bc2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='sidebar-alert']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sidebar-alert</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8e642b9f-f2d0-48ed-98a4-669f34a21995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebar-alert</value>
      <webElementGuid>98f3a619-fe4a-4467-a120-ccff4cb34d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-exclamation-circle</value>
      <webElementGuid>2b0be413-acea-451b-a71b-152681345ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Alertes</value>
      <webElementGuid>1fbdd5bc-20a9-4456-bed0-991aa89ce0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-alert&quot;)</value>
      <webElementGuid>967c2bb6-556a-46ad-b87d-821a0549f8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5fa42ed2-2ac6-4213-bce4-f1ef94d66354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebar-alert</value>
      <webElementGuid>6d4acd8c-5fe0-4fd8-8551-ccacfa1ca550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-exclamation-circle</value>
      <webElementGuid>9e5f5695-4ea4-4089-b925-36b361b19dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Alertes</value>
      <webElementGuid>ace1b455-a519-442e-a8a8-3703fc9ccafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-alert&quot;)</value>
      <webElementGuid>6138434e-6d0e-4e36-a34a-b47c349d6881</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='sidebar-alert']</value>
      <webElementGuid>6b5e24b4-e380-429c-bb53-fb6f80cfcb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='alert-managment']/span</value>
      <webElementGuid>219e3503-0c76-487b-8ff2-bb4271dbca3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>5650d342-bdc9-4d9e-96cc-c7787cf790a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'sidebar-alert' and @title = 'Alertes']</value>
      <webElementGuid>08176619-803d-4cc0-90e9-5e2f0b25c621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
